spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/wechat_login?useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai"
    username: "root"
    password: ""
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQL57Dialect"
    hibernate:
      ddl-auto: "update"

server:
  # 配置端口
  port: ${port:8082}
  servlet:
    session:
      timeout: 60m

# 公众号配置， 换成自己的配置
wx:
  mp:
    appid: xxxxxxx
    secret: xxxxxxx
    token: yunzhi
    aesKey: 123